### PR TITLE
ENH add uniform rolling sims for uniform surveys at 1, 4, 7, and 10

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds sims that implement the uniform phased rolling. 

The requested number of visits in the WFD footprint looks like this:

uniform

You can see that at years 1, 4, 7 and 10, the survey comes back to uniform. 

The adjustments to the strategy 

 - result in no loss of TD data
 - do not attempt to observe any location in ra out of phase with it's natural season
 - are coded in such a way that they will work for any survey start date

### CODE REVIEW

**Comment by beckermr** [comment]
cc @fedhere @yoachim @rhiannonlynne @rmandelb for viz

**Comment by rhiannonlynne** [comment]
It's kind of hard to see what was changed here versus in the standard setup, given the additional code that I think was maybe copied over (that maybe is now in rubin-scheduler? not sure why it's showing up in the git diff the way it is). 
I *think* the changes are in the "if uniform" part of the blob scheduling?  (please let me know if I misunderstood)

It would be really helpful for us in maintaining and using this code in the future if there were some additional comment lines to explain what was changed and why .. for example, reading it super quickly, it looks like there are just some ranges of RA which have a pause in rolling added, while other ranges are not paused. (which is what I understood to be the original goal of "pausing" rolling for variable amounts of time). But it's helpful to not have to guess or try out the code to be sure what each piece is doing.

**Comment by beckermr** [comment]
Yes absolutely. This PR was meant to confirm the changes work and be easy for Peter to run right away. 

Once we confirm it works, I'll make a pr directly to the scheduler repo to implement this as the default. I'll add tests, comments, etc as well.

**Comment by beckermr** [comment]
You are indeed correct that the changes are in the uniform branch of the make rolling footprints function. 

It adjusts the rolling so that near a data release, a portion of ra that was supposed to start rolling waits for six months and is uniformly observed instead. I tried variations of three months and that was not sufficient (for good reason).

These delay is accounted for on the other side so that the time domain data volume is preserved. Figuring this part out took a little intuition and following the symmetry of the seasons pattern. 

The same ideas are used after the next rolling cycle.

**Comment by beckermr** [comment]
I also should credit Eric G. for this idea originally.

**Pull request merged**
